CREATE TABLE `geograph` (
  `GEO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GEO_BIN` varchar(45) NOT NULL,
  `GEO_NAME` varchar(45) NOT NULL,
  `GEO_CODE` varchar(45) DEFAULT NULL,
  `GEO_LEVEL` int(11) DEFAULT NULL,
  `GEO_PARENT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`GEO_ID`),
  UNIQUE KEY `id_UNIQUE` (`GEO_ID`),
  UNIQUE KEY `GEO_BIN_UNIQUE` (`GEO_BIN`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8 COMMENT='地理表';
CREATE TABLE `schoolroll` (
  `SCH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCH_CODE` varchar(45) NOT NULL,
  `SCH_NAME` varchar(128) NOT NULL,
  `SCH_LEVEL` varchar(45) DEFAULT NULL,
  `SCH_PROP` varchar(128) DEFAULT NULL,
  `SCH_PARENT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`SCH_ID`),
  UNIQUE KEY `SCH_ID_UNIQUE` (`SCH_ID`),
  UNIQUE KEY `SCH_CODE_UNIQUE` (`SCH_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=116 DEFAULT CHARSET=utf8;
CREATE TABLE `geograph_schoolroll` (
  `GEO_ID` int(11) NOT NULL,
  `SCH_ID` int(11) NOT NULL,
  PRIMARY KEY (`GEO_ID`,`SCH_ID`),
  KEY `FK55E226D334F78597` (`SCH_ID`),
  KEY `FK55E226D36C9F4B4A` (`GEO_ID`),
  CONSTRAINT `FK55E226D334F78597` FOREIGN KEY (`SCH_ID`) REFERENCES `schoolroll` (`SCH_ID`),
  CONSTRAINT `FK55E226D36C9F4B4A` FOREIGN KEY (`GEO_ID`) REFERENCES `geograph` (`GEO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `school` (
  `SCL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCL_NAME` varchar(45) NOT NULL,
  `SCL_LEVEL` varchar(45) DEFAULT NULL,
  `SCL_PROP` varchar(45) DEFAULT NULL,
  `SCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`SCL_ID`),
  UNIQUE KEY `SCH_ID` (`SCH_ID`),
  KEY `FKC9E15B7434F78597` (`SCH_ID`),
  CONSTRAINT `FKC9E15B7434F78597` FOREIGN KEY (`SCH_ID`) REFERENCES `schoolroll` (`SCH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
CREATE TABLE `grade` (
  `GRD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GRD_NAME` varchar(45) DEFAULT NULL,
  `SCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`GRD_ID`),
  UNIQUE KEY `SCH_ID` (`SCH_ID`),
  KEY `FK5E0BFD734F78597` (`SCH_ID`),
  CONSTRAINT `FK5E0BFD734F78597` FOREIGN KEY (`SCH_ID`) REFERENCES `schoolroll` (`SCH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;
CREATE TABLE `clazz` (
  `CLZ_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLZ_NAME` varchar(45) DEFAULT NULL,
  `SCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`CLZ_ID`),
  UNIQUE KEY `SCH_ID_UNIQUE` (`SCH_ID`),
  KEY `FK5A5AA5887FA78F8` (`SCH_ID`),
  CONSTRAINT `FK5A5AA5887FA78F8` FOREIGN KEY (`SCH_ID`) REFERENCES `schoolroll` (`SCH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8;
CREATE TABLE `userinfo` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(10) NOT NULL,
  `PASSWORD` varchar(30) DEFAULT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID` (`USER_ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `authorities` (
  `AUTH_ID` int(11) NOT NULL DEFAULT '0',
  `AUTHORITY` varchar(255) NOT NULL,
  `AUTH_TYPE` varchar(32) NOT NULL,
  `PROTECTED_RES` varchar(64) NOT NULL,
  `DISPLAY` varchar(64) NOT NULL,
  `NOTE` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`AUTH_ID`),
  UNIQUE KEY `AUTH_ID` (`AUTH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `user_auth` (
  `USER_ID` int(11) NOT NULL DEFAULT '0',
  `AUTH_ID` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`USER_ID`,`AUTH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `subject` (
  `SUB_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUB_NAME` varchar(45) NOT NULL,
  `SUB_CODE` varchar(45) NOT NULL,
  `SCH_ID` int(11) NOT NULL,
  PRIMARY KEY (`SUB_ID`),
  KEY `FK90AA552C87FA78F8` (`SCH_ID`),
  CONSTRAINT `FK90AA552C87FA78F8` FOREIGN KEY (`SCH_ID`) REFERENCES `schoolroll` (`SCH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;


